openapi: "3.0.0"
info:
  title: PoliceCheck
  version: 1.0.0
paths:
  /records:
    post:
      summary: Create a record
      description: Create a record in the Criminal Records
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - email
              properties:
                email:
                  type: string
                description:
                  type: string
                severity:
                  type: integer
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  description:
                    type: string

        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  description:
                    type: string

        '500':
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string

      deprecated: false
      security: []

  /severity/{email}:
    get:
      summary: Get the severity
      description: Get the severity status of the user
      parameters:
        - name: email
          in: path
          description: Email of the user in the record
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  description:
                    type: string
                  isGuilt:
                    type: boolean

        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  description:
                    type: string

        '500':
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string

      deprecated: false
      security: []

  /records/{email}:
    delete:
      summary: Delete a user
      description: Delete a user from the Criminal Records
      parameters:
        - name: email
          in: path
          description: Email of the user in the record
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  description:
                    type: string

        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  description:
                    type: string

        '500':
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string

      deprecated: false
      security: []
  
  /records/{email}/{description:}:
    delete:
      summary: Delete a user
      description: Delete a user from the Criminal Records
      parameters:
        - name: email
          in: path
          description: Email of the user in the record
          required: true
          schema:
            type: string
        - name: description
          in: path
          description: Description of the record to be deleted
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  description:
                    type: string

        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  description:
                    type: string

        '500':
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string

      deprecated: false
      security: []